name: Compile LaTeX

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Prepare Pages
        run: |
          mkdir -p public
          cp main.pdf public/document.pdf

          cat > public/index.html <<'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Symmetries in Wick-Rotated QFTs</title>
              <meta http-equiv="refresh" content="0; url=document.pdf">
          </head>
          <body>
              <script>
                  window.location.href = "document.pdf";
              </script>
          </body>
          </html>
          EOF


      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
